Areas/Admin/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Books.Data;
using Books.Models;
using Microsoft.AspNetCore.Hosting;
using Books.Models.ViewModels;
using System.IO;
using Books.StaticDetails;
using Books.Functional.Interfaces;
using Books.Functional.Classes;

namespace Books.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        [BindProperty]
        public BookViewModel BookVM { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        IAuthorSupport AuthorSupport;

        public BookController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
            BookVM = new BookViewModel
            {
                Book = new Book() { 
                    Author01 = new Author(),
                    Author02 = new Author(),
                    Author03 = new Author(),
                    Author04 = new Author(),
                    Author05 = new Author(),
                    Cover = new Cover(),
                    Genre01 = new Genre { 
                        Category = new Category()
                    },
                    Genre02 = new Genre
                    {
                        Category = new Category()
                    },
                    Genre03 = new Genre
                    {
                        Category = new Category()
                    },
                    Genre04 = new Genre
                    {
                        Category = new Category()
                    },
                    Genre05 = new Genre
                    {
                        Category = new Category()
                    },
                    Publisher = new Publisher(),
                    Language = new Language(),
                },
                Authors = _db.Author.ToList(),
                Covers = _db.Cover.ToList(),
                Genres = _db.Genre.ToList(),
                Publishers = _db.Publisher.ToList(),
                Languages = _db.Language.ToList(),
                Categories = _db.Category.ToList()
            };
            AuthorSupport = new AuthorSupport()
            {
                WebRootPath = webHostEnvironment.WebRootPath,
                Db = db,
            };
        }

        // GET: Admin/Book
        // =================
        public async Task<IActionResult> Index()
        {
            // Get all books from database
            // ----------------------
            var books = _db.Book.Include(b => b.Author01).Include(b => b.Cover)
                                               .Include(b => b.Genre01).Include(b => b.Language)
                                               .Include(b => b.Publisher)
                                               .OrderBy(b => b.Author01.Alias).ThenBy(b => b.Name)
                                               .ToListAsync();

            // Return books to View
            // ----------------------
            return View(await books);

        }


        // GET: Admin/Book/Create
        // =================
        public IActionResult Create()
        {
            return View(BookVM);
        }

        // POST: Admin/Book/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create()
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Add(book);
        //        await _db.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["AuthorId01"] = new SelectList(_db.Author, "Id", "Name", book.AuthorId01);
        //    ViewData["CoverId"] = new SelectList(_db.Cover, "Id", "Name", book.CoverId);
        //    ViewData["GenreId01"] = new SelectList(_db.Genre01, "Id", "Name", book.GenreId01);
        //    ViewData["LanguageId"] = new SelectList(_db.Language, "Id", "Name", book.LanguageId);
        //    ViewData["PublisherId"] = new SelectList(_db.Publisher, "Id", "Name", book.PublisherId);
        //    return View(book);
        //}

        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost()
        {
            return View(BookVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async ValueTask<Tuple<short, string>> CreateAuthor(AuthorViewModel authorVM)
        {

            var status = await AuthorSupport.AuthorCreate(ModelState, authorVM, HttpContext);
            return status;
            //if (exitCode == 0)
            //{
            //    return RedirectToAction(nameof(Index));
            //}

        }

        // GET: Admin/Book/Details/id
        // =================
        public async Task<IActionResult> Details(long? id)
        {

            // Verify if Book with id exists
            // ---------------------- 
            if (id == null)
            {
                return NotFound();
            }

            var book = await _db.Book
                .Include(b => b.Author01)
                .Include(b => b.Cover)
                .Include(b => b.Genre01)
                .Include(b => b.Language)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }


        // GET: Admin/Book/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _db.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorId01"] = new SelectList(_db.Author, "Id", "Name", book.AuthorId01);
            ViewData["CoverId"] = new SelectList(_db.Cover, "Id", "Name", book.CoverId);
            ViewData["GenreId01"] = new SelectList(_db.Genre, "Id", "Name", book.GenreId01);
            ViewData["LanguageId"] = new SelectList(_db.Language, "Id", "Name", book.LanguageId);
            ViewData["PublisherId"] = new SelectList(_db.Publisher, "Id", "Name", book.PublisherId);
            return View(book);
        }

        // POST: Admin/Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,AuthorId01,ReleaseDate,CoverId,GenreId01,PublisherId,LanguageId,Image,Description,OnStock,Type,Price")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(book);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId01"] = new SelectList(_db.Author, "Id", "Name", book.AuthorId01);
            ViewData["CoverId"] = new SelectList(_db.Cover, "Id", "Name", book.CoverId);
            ViewData["GenreId01"] = new SelectList(_db.Genre, "Id", "Name", book.GenreId01);
            ViewData["LanguageId"] = new SelectList(_db.Language, "Id", "Name", book.LanguageId);
            ViewData["PublisherId"] = new SelectList(_db.Publisher, "Id", "Name", book.PublisherId);
            return View(book);
        }

        // GET: Admin/Book/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _db.Book
                .Include(b => b.Author01)
                .Include(b => b.Cover)
                .Include(b => b.Genre01)
                .Include(b => b.Language)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Admin/Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var book = await _db.Book.FindAsync(id);
            _db.Book.Remove(book);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(long id)
        {
            return _db.Book.Any(e => e.Id == id);
        }

        // GET Genres action
        // -------------------------
        [ActionName("GenreGet")]
        public async Task<IActionResult> GenreGet(short id)
        {
            // Create genres object
            // -------------------------
            List<Genre> genres = new List<Genre>();

            // get genres from database with requested category id
            // -------------------------
            genres = await (from genre in _db.Genre
                            where genre.CategoryId == id
                            select genre).ToListAsync();

Areas/Admin/Controllers/CoverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Books.Data;
using Books.Models;

namespace Books.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CoverController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: Admin/Cover
        // -------------------------
        public async Task<IActionResult> Index()
        {
            return View(await _db.Cover.OrderBy(c => c.Name).ToListAsync());
        }

        // GET: Admin/Cover/Create
        // -------------------------
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Cover/Create
        // -------------------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cover cover)
        {
            if (ModelState.IsValid)
            {
                _db.Cover.Add(cover);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(cover);
        }

        // GET: Admin/Cover/Edit
        // -------------------------
        public async Task<IActionResult> Edit(short? id)
        {
            // Check if id was properly sent
            // -------------------------
            if (id == null)
            {
                return NotFound();
            }

            // If Id was properly sent then get Publisher from Db
            // -------------------------
            var cover = await _db.Cover.FindAsync(id);

            // If Publisher with such Id wasn't found then show Not Found screen
            // -------------------------
            if (cover == null)
            {
                return NotFound();
            }

            // If all commands passed then display proper View
            // -------------------------
            return View(cover);
        }

        // POST: Admin/Cover/Edit
        // -------------------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,Name")] Cover cover)
        {
            // Validate id number
            // -------------------------
            if (id != cover.Id)
            {
                return NotFound();
            }

            // Validate model state
            // -------------------------
            if (ModelState.IsValid)
            {
                // Try to update Cover name
                // -------------------------
                try
                {
                    _db.Update(cover);
                    await _db.SaveChangesAsync();
                }
                // If cover update fails then throw an error page
                // -------------------------
                catch (DbUpdateConcurrencyException)
                {
                    // Check if selected cover exists in database
                    // -------------------------
                    if (!CoverExists(cover.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Redirect to action page
                // -------------------------
                return RedirectToAction(nameof(Index));
            }

            // If model state is invalid go back to Edit page
            // -------------------------
            return View(cover);
        }

        // GET: Admin/Cover/Delete
        // -------------------------
        public async Task<IActionResult> Delete(short? id)
        {
            // Check if id was properly sent
            // -------------------------
            if (id == null)
            {
                return NotFound();
            }

            // If Id was properly sent then get Cover from Db
            // -------------------------
            var cover = await _db.Cover
                .FirstOrDefaultAsync(m => m.Id == id);

            // If Cover with such Id wasn't found then show Not Found screen
            // -------------------------
            if (cover == null)
            {
                return NotFound();
            }

            // If all commands passed then display proper View
            // -------------------------
            return View(cover);
        }

        // POST: Admin/Cover/Delete
        // -------------------------
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short? id)
        {
            // Check if id was properly sent
            // -------------------------
            if (id == null)
            {
                return NotFound();
            }

            // Search for cover with specified id
            // -------------------------
            var cover = await _db.Cover.FindAsync(id);

            // Check if cover exists in database
            // -------------------------
            if (cover == null)
            {
                return NotFound();
            }

            // If cover exists then remove it from database
            // -------------------------
            _db.Cover.Remove(cover);
            await _db.SaveChangesAsync();

            // Go back into index action
            // -------------------------
            return RedirectToAction(nameof(Index));
        }

        private bool CoverExists(short id)
        {
            return _db.Cover.Any(e => e.Id == id);
        }
    }
}

Views/Shared/DeleteAndBackButtonsPartial.cshtml
@model short

<div class="row">
    <div class="col-6">
        <input class="btn btn-outline-dark form-control" type="submit" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a class="btn btn-outline-dark form-control" asp-action="Index"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
    </div>
</div>

Views/Shared/_CreateAndBackButtonsPartial.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-outline-dark form-control" id="createBtn" value="Create"/>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-outline-dark form-control"><i class="fas fa-arrow-left"></i> &nbsp; Back</a>
    </div>
</div>

Views/Shared/_CreateButtonGreenPartial.cshtml
@model string

<a id="@Model" asp-action="Create" class="offset-1 btn btn-outline-success mx-1 px-2 py-1 my-0"><i class="fas fa-plus-circle"></i>
</a>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-outline-dark"><i class="fas fa-plus"></i> &nbsp; Create</a>
</p>

Views/Shared/_DeleteAndBackButtonsPartial.cshtml
@model short

<div class="row">
    <div class="col-6">
        <input class="btn btn-outline-dark form-control" type="submit" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a class="btn btn-outline-dark form-control" asp-action="Index"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
    </div>
</div>

Views/Shared/_DeleteYesAndNoButtonsPartial.cshtml
@model short

<div class="row">
    <div class="col-6">
        <input asp-action="Delete" class="btn btn-outline-dark form-control" type="submit" asp-route-id="@Model" value="Yes" />
    </div>
    <div class="col-6">
        <button class="btn btn-outline-dark form-control" data-dismiss="modal">No</button>
    </div>
</div>

Views/Shared/_EditAndBackButtonsPartial.cshtml
@model Int16

<div class="row">
    <div class="col-6">
        <input type="submit" asp-route-id="@Model" class="btn btn-outline-dark form-control" value="Edit">
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-outline-dark form-control"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
    </div>
</div>

Views/Shared/_EditAndBackToDetailsButtonsPartial.cshtml
@model Int16

<div class="row">
    <div class="col-6">
        <input type="submit" asp-route-id="@Model" class="btn btn-outline-dark form-control" value="Edit">
    </div>
    <div class="col-6">
        <button class="btn btn-outline-dark form-control" id="backButton"><i class="fas fa-arrow-left"></i>&nbsp; Back</button>
    </div>
</div>

Views/Shared/_EditAndDeleteButtonsBytePartial.cshtml
@* Id value of selected element 
   ----------------------------*@
@model byte


<div class="btn-group" role="group">
    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@Model">
        <i class="fas fa-edit"></i>
    </a>
    <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i>
    </a>
</div>

Views/Shared/_EditAndDeleteButtonsPartial.cshtml
@* Id value of selected element 
   ----------------------------*@
@model System.Int16


<div class="btn-group" role="group">
    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@Model">
        <i class="fas fa-edit"></i>
    </a>
    <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i>
    </a>
</div>

Views/Shared/_EditDeleteBackButtonsPartial.cshtml
@model short

<div class="row">
    <div class="col-3">
        <a asp-action="Edit" class="btn btn-outline-dark form-control" asp-route-id="@Model" id="editButton"><i class="fas fa-edit"></i>&nbsp; Edit</a>
    </div>
    <div class="col-3">
        <button class="btn btn-outline-dark form-control" id="deleteButton"><i class="fas fa-trash"></i>&nbsp; Delete</button>
    </div>
    <div class="col-3">
        <a asp-action="Index" class="btn btn-outline-dark form-control"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
    </div>
</div>

Views/Shared/_EditDetailsDeleteButtonsPartial.cshtml
@* Id value of selected element 
   ----------------------------*@
@model System.Int16


<div class="btn-group" role="group">
    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@Model">
        <i class="fas fa-edit"></i>
    </a>
    <a class="btn btn-outline-dark" asp-action="Details" asp-route-id="@Model">
        <i class="fas fa-list"></i>
    </a>
    <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i>
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
</head>
<body>
    <header class="position-fixed col-12 p-0" style="z-index:10000">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    @* I've had some issues with setting height and width in percent units *@
                    <img src="~/img/Books.logo2.png" alt="Books logo" title="Books" width="100" />
                </a>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Bestsellers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Coupon</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse offset-3">
                    <ul class="navbar-nav flex-grow-1">
                        @* classes explanation:
                            dropdown -          displays list of items below button
                            dropdown-toggle -   displays arrow that indicates that button is a list
                        *@
                        <li class="nav-item dropdown">
                            <a class="text-dark nav-link dropdown-toggle" href="#" id="navbarDropDownContentsLink"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage Contents
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownContentsLink">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Author" asp-action="Index">Authors</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Publisher" asp-action="Index">Publishers</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">Coupons</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Genre" asp-action="Index">Genres</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Cover" asp-action="Index">Covers</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Language" asp-action="Index">Languages</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Manage Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <br /> <br /> <br /> <br />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Books - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_StatusMessagePartial.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.ToLower().StartsWith("error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible " role="alert">
        <button type="button" class="close" data-dismiss="alert"
                arial-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Model
    </div>
}